# Site settings
title: Damillora
email: duniapengetahuan.12345@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  programming, anime, and lots of other things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://damillora.github.io" # the base hostname & protocol for your site
twitter_username: Damillora
github_username:  Damillora
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
facebook_app_id: 12345

# Layout settings
header_type: drawer  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: NitroKIR IT
    link: nitrokir-it.github.io

disqus: true
disqus_shortname: 'damillora''

# Build settings
markdown: kramdown
